import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { GitBranch, Plus, Trash2 } from 'lucide-react';
import { BaseApiClient } from '@/services/baseApiClient';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

type Provider = 'gitlab' | 'bitbucket'; interface Integration { id: string; provider: Provider; name: string; host: string; username: string }
class Api extends BaseApiClient { protected resource = 'source-integrations'; list() { return this.get<Integration[]>(); } create(data: Omit<Integration, 'id'> & { token: string }) { return this.post<Integration>('', data); } remove(id: string) { return this.delete<void>(`/${id}`); } } const api = new Api();
export function SourceIntegrationsSettings() {
  const [provider, setProvider] = useState<Provider>('gitlab'); const [name, setName] = useState(''); const [host, setHost] = useState('gitlab.com'); const [username, setUsername] = useState('oauth2'); const [token, setToken] = useState(''); const qc = useQueryClient(); const key = ['source-integrations'];
  const query = useQuery({ queryKey: key, queryFn: () => api.list() }); const refresh = () => qc.invalidateQueries({ queryKey: key });
  const create = useMutation({ mutationFn: () => api.create({ provider, name: name || provider, host, username, token }), onSuccess: () => { setToken(''); refresh(); } }); const remove = useMutation({ mutationFn: (id: string) => api.remove(id), onSuccess: refresh });
  return <Card><CardHeader><CardTitle className="text-base">GitLab &amp; Bitbucket</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-muted-foreground text-sm">Tokens are encrypted and injected only into agent clone URLs for the matching host.</p><div className="grid gap-2 md:grid-cols-5"><Select value={provider} onValueChange={(value) => { const next = value as Provider; setProvider(next); setHost(next === 'gitlab' ? 'gitlab.com' : 'bitbucket.org'); setUsername(next === 'gitlab' ? 'oauth2' : 'x-token-auth'); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="gitlab">GitLab</SelectItem><SelectItem value="bitbucket">Bitbucket</SelectItem></SelectContent></Select><Input placeholder="Name" value={name} onChange={(event) => setName(event.target.value)} /><Input placeholder="Host" value={host} onChange={(event) => setHost(event.target.value)} /><Input placeholder="Username" value={username} onChange={(event) => setUsername(event.target.value)} /><Input type="password" placeholder="Access token" value={token} onChange={(event) => setToken(event.target.value)} /></div><Button disabled={token.length < 8} onClick={() => create.mutate()}><Plus className="size-4" /> Connect</Button><div className="divide-y rounded border">{query.data?.map((item) => <div key={item.id} className="flex items-center justify-between p-3"><span className="flex items-center gap-2"><GitBranch className="size-4" /> {item.name} <span className="text-muted-foreground text-sm">{item.username}@{item.host}</span></span><Button variant="ghost" size="icon" onClick={() => remove.mutate(item.id)}><Trash2 className="text-destructive size-4" /></Button></div>)}</div></CardContent></Card>;
}
