import { useQuery } from '@tanstack/react-query';
import { useParams } from 'react-router-dom';
interface Page { title: string; description: string; overall: string; services: Array<{ id: string; name: string; state: string }>; incidents: Array<{ id: string; title: string; message: string; resolved: boolean; createdAt: string }> }
export function PublicStatusPage() {
  const { slug = '' } = useParams(); const query = useQuery({ queryKey: ['public-status', slug], queryFn: async () => { const response = await fetch(`/api/status/${encodeURIComponent(slug)}`); if (!response.ok) throw new Error('Status page not found'); return response.json() as Promise<Page>; }, refetchInterval: 30_000 });
  if (query.isLoading) return <main className="mx-auto max-w-3xl p-8">Loading status…</main>;
  if (!query.data) return <main className="mx-auto max-w-3xl p-8">Status page unavailable.</main>;
  const page = query.data; return <main className="mx-auto max-w-3xl space-y-8 p-6 md:p-12"><header><p className="text-primary text-sm font-semibold">Berth Status</p><h1 className="text-3xl font-bold">{page.title}</h1><p className="text-muted-foreground mt-2">{page.description}</p></header><div className={`rounded-lg p-4 font-medium ${page.overall === 'operational' ? 'bg-emerald-500/10 text-emerald-600' : 'bg-amber-500/10 text-amber-600'}`}>{page.overall === 'operational' ? 'All systems operational' : 'Some systems are degraded'}</div><section className="divide-y rounded-lg border">{page.services.map((service) => <div key={service.id} className="flex justify-between p-4"><span>{service.name}</span><span className={service.state === 'running' ? 'text-emerald-600' : 'text-amber-600'}>{service.state}</span></div>)}</section><section><h2 className="mb-3 text-xl font-semibold">Incidents</h2>{page.incidents.length ? page.incidents.map((incident) => <article key={incident.id} className="mb-3 rounded-lg border p-4"><div className="flex justify-between"><strong>{incident.title}</strong><span>{incident.resolved ? 'Resolved' : 'Investigating'}</span></div><p className="text-muted-foreground mt-2">{incident.message}</p></article>) : <p className="text-muted-foreground">No incidents reported.</p>}</section></main>;
}
