ALTER TABLE "Organization" ADD COLUMN "alertsEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "alertCpuPct" INTEGER NOT NULL DEFAULT 90,
  ADD COLUMN "alertMemPct" INTEGER NOT NULL DEFAULT 90,
  ADD COLUMN "alertDiskPct" INTEGER NOT NULL DEFAULT 90,
  ADD COLUMN "alertMinutes" INTEGER NOT NULL DEFAULT 5;

ALTER TABLE "Service" ADD COLUMN "alertsMuted" BOOLEAN NOT NULL DEFAULT false;
