import type { AppTemplate } from './interfaces';

export const APP_TEMPLATES: AppTemplate[] = [
  {
    kind: 'n8n',
    name: 'n8n',
    description: 'Workflow automation with 400+ integrations.',
    category: 'app',
    icon: 'Workflow',
    accent: '#EA4B71',
    image: 'n8nio/n8n',
    defaultTag: 'latest',
    port: 5678,
    volumePath: '/home/node/.n8n',
    env: [
      { key: 'GENERIC_TIMEZONE', value: 'UTC' },
      { key: 'N8N_ENCRYPTION_KEY', generate: true, isSecret: true },
    ],
  },
  {
    kind: 'uptime-kuma',
    name: 'Uptime Kuma',
    description: 'Self-hosted uptime monitoring with status pages.',
    category: 'tooling',
    icon: 'Activity',
    accent: '#5CDD8B',
    image: 'louislam/uptime-kuma',
    defaultTag: '1',
    port: 3001,
    volumePath: '/app/data',
  },
  {
    kind: 'grafana',
    name: 'Grafana',
    description: 'Dashboards and visualization for metrics and logs.',
    category: 'tooling',
    icon: 'LineChart',
    accent: '#F46800',
    image: 'grafana/grafana-oss',
    defaultTag: 'latest',
    port: 3000,
    volumePath: '/var/lib/grafana',
    env: [{ key: 'GF_SECURITY_ADMIN_PASSWORD', generate: true, isSecret: true }],
  },
  {
    kind: 'ghost',
    name: 'Ghost',
    description: 'Publishing platform for blogs and newsletters (SQLite).',
    category: 'app',
    icon: 'BookOpen',
    accent: '#394047',
    image: 'ghost',
    defaultTag: '5-alpine',
    port: 2368,
    volumePath: '/var/lib/ghost/content',
    env: [
      { key: 'database__client', value: 'sqlite3' },
      { key: 'database__connection__filename', value: '/var/lib/ghost/content/data/ghost.db' },
      { key: 'url', value: 'http://localhost:2368' },
    ],
  },
  {
    kind: 'gitea',
    name: 'Gitea',
    description: 'Lightweight self-hosted Git service.',
    category: 'tooling',
    icon: 'GitBranch',
    accent: '#609926',
    image: 'gitea/gitea',
    defaultTag: 'latest',
    port: 3000,
    volumePath: '/data',
  },
  {
    kind: 'vaultwarden',
    name: 'Vaultwarden',
    description: 'Bitwarden-compatible password manager server.',
    category: 'app',
    icon: 'KeyRound',
    accent: '#175DDC',
    image: 'vaultwarden/server',
    defaultTag: 'latest',
    port: 80,
    volumePath: '/data',
  },
  {
    kind: 'memos',
    name: 'Memos',
    description: 'Privacy-first note-taking and microblogging.',
    category: 'app',
    icon: 'StickyNote',
    accent: '#D9A23A',
    image: 'neosmart/memos',
    defaultTag: 'stable',
    port: 5230,
    volumePath: '/var/opt/memos',
  },
  {
    kind: 'metabase',
    name: 'Metabase',
    description: 'Business intelligence and analytics for your databases.',
    category: 'tooling',
    icon: 'BarChart3',
    accent: '#509EE3',
    image: 'metabase/metabase',
    defaultTag: 'latest',
    port: 3000,
    volumePath: '/metabase-data',
    env: [{ key: 'MB_DB_FILE', value: '/metabase-data/metabase.db' }],
  },
  {
    kind: 'nocodb',
    name: 'NocoDB',
    description: 'Open-source Airtable alternative on top of your database.',
    category: 'app',
    icon: 'Table2',
    accent: '#2F6FED',
    image: 'nocodb/nocodb',
    defaultTag: 'latest',
    port: 8080,
    volumePath: '/usr/app/data',
  },
  {
    kind: 'mailpit',
    name: 'Mailpit',
    description: 'Email testing server with a web inbox.',
    category: 'tooling',
    icon: 'Mail',
    accent: '#2E7D9A',
    image: 'axllent/mailpit',
    defaultTag: 'latest',
    port: 8025,
    volumePath: '/data',
    env: [{ key: 'MP_DATABASE', value: '/data/mailpit.db' }],
  },
  {
    kind: 'adminer',
    name: 'Adminer',
    description: 'Single-file database management UI.',
    category: 'tooling',
    icon: 'DatabaseZap',
    accent: '#34567C',
    image: 'adminer',
    defaultTag: 'latest',
    port: 8080,
  },
  {
    kind: 'linkding',
    name: 'Linkding',
    description: 'Minimal self-hosted bookmark manager.',
    category: 'app',
    icon: 'Bookmark',
    accent: '#5856E0',
    image: 'sissbruecker/linkding',
    defaultTag: 'latest',
    port: 9090,
    volumePath: '/etc/linkding/data',
    env: [
      { key: 'LD_SUPERUSER_NAME', value: 'admin' },
      { key: 'LD_SUPERUSER_PASSWORD', generate: true, isSecret: true },
    ],
  },
  {
    kind: 'changedetection',
    name: 'changedetection.io',
    description: 'Watch web pages for changes and get notified.',
    category: 'tooling',
    icon: 'Eye',
    accent: '#3E7BE0',
    image: 'ghcr.io/dgtlmoon/changedetection.io',
    defaultTag: 'latest',
    port: 5000,
    volumePath: '/datastore',
  },
  {
    kind: 'excalidraw',
    name: 'Excalidraw',
    description: 'Virtual whiteboard for sketching diagrams.',
    category: 'app',
    icon: 'PenTool',
    accent: '#6965DB',
    image: 'excalidraw/excalidraw',
    defaultTag: 'latest',
    port: 80,
  },
  {
    kind: 'nginx',
    name: 'Nginx',
    description: 'Static web server, ready to extend with your own image.',
    category: 'tooling',
    icon: 'Globe',
    accent: '#009639',
    image: 'nginx',
    defaultTag: 'alpine',
    port: 80,
  },
];
